### ISSUE TITLE
[Bug] Incorrect version range

### ISSUE THREAD

**Issue by lexisother** [Bocz3k/more-ladders#10]
# Bug report

## Info
Minecraft version: 1.20.6
Mod version: 1.5.1-1.20.5

## Bug description
Mod marked on Modrinth as supporting 1.20.5 and 1.20.6, but for some reason Fabric disagrees.
```
Mod 'More Ladders' (moreladders) 1.5.1-1.20.5 requires version 1.20.5 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.6!
```

**Comment by nieboczek** [comment]
updated the necessary files, just download the v1.5.1 1.20.5 MoreLadders again (i reuploaded the version so it should be fixed)
