### ISSUE TITLE
[Bug] 1.21 no recipes

### ISSUE THREAD

**Issue by makumaku1974** [Bocz3k/more-ladders#11]
# Bug report

## Info

Minecraft version: 
Mod version: 
Log file:

**Comment by nieboczek** [comment]
fixed, you can download the fixed version from [github](https://github.com/nieboczek/more-ladders/releases/tag/v1.5.1-1.21), [modrinth](https://modrinth.com/mod/moreladders/version/1.5.1-1.21) or curseforge (once it will get approved)
