### ISSUE TITLE
ladder -> trapdoor support

### ISSUE THREAD

**Issue by ilnomR0** [Bocz3k/more-ladders#12]
# Feature Request: Seamless Trapdoor-Ladder Interaction for More Ladders

**Description:**

I propose adding the same seamless trapdoor-ladder interaction that exists in vanilla Minecraft to the ladders provided by the More Ladders mod. This would allow players to:

*   **Climb Up:** Directly from a More Ladders ladder onto an open trapdoor above them without jumping or manually opening it.
*   **Climb Down:** Directly from an open trapdoor onto a More Ladders ladder below them without interruption.

**Benefits:**

*   **Enhanced Consistency:** Modded ladders would feel more integrated with vanilla gameplay.
*   **Improved Usability:** Streamlined navigation in structures using ladders and trapdoors (attics, basements, treehouses, etc.).
*   **Increased Realism:**  Mimics real-world ladder and trapdoor interactions.

**Technical Considerations:**

This likely involves detecting when a More Ladders ladder is under an open trapdoor and adjusting player movement logic for a smooth transition.

**Additional Notes:**

This feature is present in vanilla Minecraft (Java and Bedrock), but inconsistent in Bedrock. Adding it to More Ladders ensures a consistent experience across both editions.

**Reasoning:**

The seamless trapdoor-ladder interaction is convenient and realistic in vanilla Minecraft. Incorporating it into More Ladders would enhance the player experience and make the mod feel even more intuitive.

**Comment by nieboczek** [comment]
implemented it, you can download the new verison from [here](https://github.com/nieboczek/more-ladders/releases) and from other sources when they review it and accept it
