### ISSUE TITLE
support for modded woods like Wilder Wild, Regions Unexplored, etc...

### ISSUE THREAD

**Issue by makumaku1974** [Bocz3k/more-ladders#14]
I could provide textures on ladders but not entirely all since busy writing.

**Comment by nieboczek** [comment]
If you could provide the textures I would be happy to add support for other wood types, you can message me on Discord or here.

**Comment by makumaku1974** [comment]
Just leave this open and I'll start anytime soon.

**Comment by nieboczek** [comment]
Can you tell me what types of resources you're making ladder textures for? Also, can you tell me which mods these resource types are from? I can't start to add support without this information.

**Comment by makumaku1974** [comment]
Regions Unexplored:
![image](https://github.com/user-attachments/assets/104dfdf5-236f-45f6-9d75-24c93354ef13)

Biome's o Plenty:
![image](https://github.com/user-attachments/assets/4ddd329f-70cb-40e5-9def-fda0659bd3d5)

Blockus:
![image](https://github.com/user-attachments/assets/3a128a37-0509-4a46-acff-ff0631e657d0)

I am merely only focusing on wood types like what you did with your mod.

**Comment by nieboczek** [comment]
Have you made any ladder textures yet?

**Comment by makumaku1974** [comment]
> Have you made any ladder textures yet?

Sadly will have to close this for now since im too busy with a lot of stuff irl. I'd draft this first, after doing Balkon's Weapons revising textures. This would start.
