### ISSUE TITLE
[Bug] can't craft anything on 1.20.5

### ISSUE THREAD

**Issue by nickademas** [Bocz3k/more-ladders#9]
# Bug report

## Info

Minecraft version: 1.20.5
Mod version: 1.5.1-1.20.5
Log file: 
[latest.log](https://github.com/Bocz3k/more-ladders/files/15135755/latest.log)

## Screenshots

![obraz](https://github.com/Bocz3k/more-ladders/assets/46594867/55c30658-96ea-43d9-bcbb-f6fd1aba8029)
![obraz](https://github.com/Bocz3k/more-ladders/assets/46594867/3f8caeb0-c9a9-4b74-ad06-4c341c8e0150)

**Comment by nieboczek** [comment]
updated the recipe files, just download the v1.5.1 1.20.5 MoreLadders again (i reuploaded the version so it should be fixed)
